name: Scan kubernetes vulnerability
on:
  workflow_call:
    inputs:
      chartFolder:
        required: false
        type: string
        default: 'charts'

jobs:
  vulnerability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      # This prepares directory where github/codeql-action/upload-sarif@v1 looks up report files by default.
      - name: Create ../results directory for SARIF report files
        shell: bash
        run: mkdir -p ../results
#      - name: Scan yaml files with kube-linter
#        uses: stackrox/kube-linter-action@v1.0.5
#        id: kube-linter-action-scan
#        with:
#          # Adjust this directory to the location where your kubernetes resources and helm charts are located.
##          directory: ./target/chart/
#          directory: ${{ inputs.chartFolder }}
#          # Adjust this to the location of kube-linter config you're using, or remove the setting if you'd like to use
#          # the default config.
#          # Example config file:	https://github.com/stackrox/kube-linter-action/blob/main/sample/.kube-linter-config.yml
#          # KubeLinter includes the following built-in checks:  https://github.com/stackrox/kube-linter/blob/main/docs/generated/checks.md
#          #config: sample/.kube-linter-config.yaml
#          # The following two settings make kube-linter produce scan analysis in SARIF format which would then be
#          # made available in GitHub UI via upload-sarif action below.
#          format: sarif
#          output-file: ../results/kube-linter.sarif
#        # The following line prevents aborting the workflow immediately in case your files fail kube-linter checks.
#        # This allows the following upload-sarif action to still upload the results to your GitHub repo.
#        continue-on-error: true
#
#      # - name: Print scan outcome
#      #   run: echo ${{ steps.kube-linter-action-scan.outcome }}
#
#      - name: Upload SARIF report files to GitHub
#        uses: github/codeql-action/upload-sarif@v3
#        with:
#          sarif_file: ../results/kube-linter.sarif
#
#      # # Ensure the workflow eventually fails if files did not pass kube-linter checks.
#      # - name: Verify kube-linter-action succeeded
#      #   shell: bash
#      #   run: |
#      #     echo "If this step fails, kube-linter found issues. Check the output of the scan step above."
#      #     [[ "${{ steps.kube-linter-action-scan.outcome }}" == "success" ]]
#
#      - name: PWD
#        shell: bash
#        run: pwd

      - name: kube-score check
        uses: piraces/kube-score-ga@0eb83dcf2274cf7018257df01feb5d2f43f7cb59 # v0.1.3
        id: kube-score-check
        with:
          manifests-folders: templates/*.yaml
          output-file: ../results/kube-score.txt
          ignore-exit-code: 'false'
        continue-on-error: false

