name: Auto Labeler
on:
  workflow_call: {}

jobs:
  auto-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run auto-labeler
        id: auto-labeler
        uses: mauroalderete/action-assign-labels@671a4ca2da0f900464c58b8b5540a1e07133e915 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          conventional-commits: |
            conventional-commits:
              - type: 'fix'
                nouns: ['FIX', 'Fix', 'fix', 'FIXED', 'Fixed', 'fixed']
                labels: ['fix']
              - type: 'feature'
                nouns: ['FEATURE', 'Feature', 'feature', 'FEAT', 'Feat', 'feat']
                labels: ['feature']
              - type: 'breaking_change'
                nouns: ['BREAKING CHANGE', 'BREAKING', 'MAJOR']
                labels: ['BREAKING CHANGE']
              - type: 'documentation'
                nouns: ['doc', 'docs', 'docu','document','documentation']
                labels: ['documentation','fix']
              - type: 'ci'
                nouns: ['build','rebuild','ci']
                labels: ['ci']
              - type: 'dependencies'
                nouns: ['build(deps)','build(deps-dev)', 'fix(deps)']
                labels: ['ci','dependencies']
              - type: 'config'
                nouns: ['config', 'conf', 'configuration', 'configure']
                labels: ['config','fix']
              - type: 'chore'
                nouns: ['chore']
                labels: ['chore','fix']